### ISSUE TITLE
Not really an issue just an possible speed upgrade

### ISSUE THREAD

**Issue by Tray2** [PlannrCrm/laravel-fast-refresh-database#3]
In many of my test files I run a before each function where I seed a static table.
The content of this table would never change from inside the application.   

```php
beforeEach(function () {
  $this->seed(MediaTypeSeeder::class);
});
```

So my thought is that if it somehow would be possible to add some kind of FastTableSeeder trait. that takes an array of seeder classes and keeps track of the checksum, and only runs them if needed, just like the migration:fresh.

In my case we are talking about 4 records, but for around 300 tests it becomes 1200 inserts, which takes time. 

And maybe you want to be able force a run for each test file in the suite.

**Comment by krzysztofrewak** [comment]
I was thinking about the same issue. Maybe the better approach would be to run all migrations with seeders once and then created a dump of entire "base" database. With this approach `migrate:fresh` would not be ran anymore as we would need to recreate a dump file.

**Comment by Tray2** [comment]
That is an option, but I feel that you shouldn't run any seeders that you don't need.

**Comment by sinnbeck** [comment]
If you set the seeder on your TestCase class it will automatically be seeded with the migrations (once). Just be aware that changes to this seeder will require that you manually delete or alter the checksum file

```
public $seeder = SomeSeeder::class

**Comment by Tray2** [comment]
I tried that, but it didn't make any difference with seeding of around 3K records in one seeder.

**Comment by Tray2** [comment]
I think this one can be closed without further a do
