### ISSUE TITLE
getCachedMigrationChecksum always returns null

### ISSUE THREAD

**Issue by larskoole** [PlannrCrm/laravel-fast-refresh-database#4]
For some odd reason, the `getCachedMigrationChecksum` method returns `null` when using the `rescue` method:

```PHP
protected function getCachedMigrationChecksum(): ?string
{
    return rescue(static fn () => file_get_contents($this->getMigrationChecksumFile()), null, false);
}

// null
```

When I change it to only use `file_get_contents($this->getMigrationChecksumFile())` it works fine.

```PHP
protected function getCachedMigrationChecksum(): ?string
{
    return file_get_contents($this->getMigrationChecksumFile());
}

// d99e0d21f2061fbe53ae73fb885...
```

No idea why it does this or how to fix it.

Let me know if you need more info!

**Comment by deligoez** [comment]
it is the same with me too, tried on php 8.1 and 8.2

**Comment by Sammyjo20** [comment]
This issue should be fixed in the latest release, thanks for raising this!
