### ISSUE TITLE
RefreshDatabase and FastRefreshDatabase is not workable with Laravel Dusk

### ISSUE THREAD

**Issue by dr41d45** [PlannrCrm/laravel-fast-refresh-database#6]
I would avoid the `__DIR__` variable in the Pest file
https://github.com/PlannrCrm/laravel-fast-refresh-database/blob/55052efd70ea24fc29ba530bf2dd9b68e97592cd/.github/README.md?plain=1#L57
due the `RefreshDatabase` trait is not  compatible with Laravel Dusk, which uses only the `DatabaseMigrations` trait. Source: https://laravel.com/docs/9.x/dusk#migrations.
My suggestion to document:
`uses(FastRefreshDatabase::class)->in('Feature');`
instead of 
`uses(FastRefreshDatabase::class)->in(__DIR__);`

**Comment by Sammyjo20** [comment]
That's a good shout, I thnk it might be good to note this in the documentation?

**Comment by craigpotter** [comment]
Closing this issue as #13 was merged.
